## 2021-1018 don't think need this, 
## workflow docker-publish.yml should build and push to ghcr.io
## which could be done via schedule or push to branch, so that one is preferred over this one.

name: Docker Image CI

on:
  push:
    #branches: [ main ]
    branches: [ disabled ]
  pull_request:
    branches: [ main ]
## branch name is main, not master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag atlas:$(date +%Y%m%d_%H%M)
